### ISSUE TITLE
BGP confederations?

### ISSUE THREAD

**Issue by blakedot** [mhmxs/calico-route-reflector-operator-proposal#5]
Greetings,
Thanks for putting this together & making it public, it's a very interesting & well-thought-out scaling exercise.

Just out of curiosity, had you considered using BGP confederations at the top level, as a way to avoid having to manage route-reflector hierarchy?
I find their concept of an internal network border quite useful e.g. between continents, metro areas, datacenters, etc (depending on the density of the network, of course).
32-bit private ASNs make confederations a more viable tool than when they were introduced, as the range is large enough to encode two or three octets of the router ID, etc.

Take care & best regards,
-Blake

**Comment by mhmxs** [comment]
@blakedot Thank you and welcome :) Based on our knowledge the `Multi cluster` would fit of 95+% of the Calico users, because it scales well and simple in the same time. So our main goal for the first version is that topology. Because Calico supports route reflectors and will for a long term the scope of this development is to be able to scale it well. But anyway I like the idea, and i suggest to you to create a feature request in [Calico issue tracker](https://github.com/projectcalico/calico/issues/new/choose), write a proposal, or simple discuss it on [Slack](https://calicousers.slack.com/archives/C1J26M73P).
